# Generated by Django 4.0.4 on 2022-04-21 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocoin',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='cryptocoin',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CryptoHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='crypto_app.cryptocoin')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='crypto_app.portfolio')),
            ],
        ),
    ]
