# Generated by Django 4.0.4 on 2022-04-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0002_remove_cryptocoin_coins_remove_cryptocoin_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoholdings',
            name='coin',
        ),
        migrations.AddField(
            model_name='cryptoholdings',
            name='coin_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CryptoCoin',
        ),
    ]
